name: run tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: lukka/get-cmake@latest

      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: '9edb1b8e590cc086563301d735cae4b6e732d2d2'
          runVcpkgInstall: true
          doNotCache: false
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: run tests
        uses: lukka/run-cmake@v10
        with:
          workflowPreset: run-tests
